//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMHCollegeSalaryMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMHCollegeSalaryMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon rsc_icon_mmh_logo {
            get {
                object obj = ResourceManager.GetObject("rsc_icon_mmh_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsc_image_mmh_logo {
            get {
                object obj = ResourceManager.GetObject("rsc_image_mmh_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsc_image_mmh_logo_login {
            get {
                object obj = ResourceManager.GetObject("rsc_image_mmh_logo_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string rsc_string_cell_pos_bank_acc_no {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_bank_acc_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string rsc_string_cell_pos_bank_loan {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_bank_loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string rsc_string_cell_pos_basic_pay {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_basic_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string rsc_string_cell_pos_cca {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_cca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string rsc_string_cell_pos_da {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string rsc_string_cell_pos_designation {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string rsc_string_cell_pos_glip {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_glip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string rsc_string_cell_pos_gpf {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_gpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string rsc_string_cell_pos_gpf_loan {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_gpf_loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string rsc_string_cell_pos_grade_pay {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_grade_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string rsc_string_cell_pos_gross_salary {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_gross_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string rsc_string_cell_pos_hra {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_hra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string rsc_string_cell_pos_income_tax {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_income_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string rsc_string_cell_pos_indx {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_indx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string rsc_string_cell_pos_name {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string rsc_string_cell_pos_net_salary {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_net_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string rsc_string_cell_pos_other_fp {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_other_fp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string rsc_string_cell_pos_pan {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string rsc_string_cell_pos_recovery {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string rsc_string_cell_pos_total_deduction {
            get {
                return ResourceManager.GetString("rsc_string_cell_pos_total_deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string rsc_string_password_admin {
            get {
                return ResourceManager.GetString("rsc_string_password_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string rsc_string_password_default {
            get {
                return ResourceManager.GetString("rsc_string_password_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string rsc_string_user_name {
            get {
                return ResourceManager.GetString("rsc_string_user_name", resourceCulture);
            }
        }
    }
}
